
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";

// This is class that describes you smart contract.
contract BaseStation is GameObject {

    constructor(uint _health) public {
        health = _health;
        
    }

   //  function setHealth(val) public override {
       // health = val;
   // }
    
    mapping (uint=>address) unit;
    


}
