
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";

// This is class that describes you smart contract.
contract BaseStation is GameObject {

    uint public station;

    constructor(int _health) public {
        health = _health;
        
    }

    struct Unit {
        uint health;
        uint power;
        address unitAddress;    
    }

    Unit[] units;

    function addUnit(uint health, uint power ) virtual external {
        address unitAddress = msg.sender;
        units.push(Unit(health, power, unitAddress));

    }



   //  function setHealth(val) public override {
       // health = val;
   // }
    
   
    


}
