
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";


// This is class that describes you smart contract.
contract BaseStation is GameObject  {


    constructor(int _health) public {
        health = _health;
        tvm.accept();
        
    }

    address[] unitAddres;

    mapping (address=>uint) mapOfUnit;

    function addUnit(address val) public     {
        tvm.accept();
        val = msg.sender;
        unitAddres.push(val);
        uint id = unitAddres.length - 1;
        mapOfUnit[val] = id;


    }

    function delUnit(address val) public {
        tvm.accept();
        val = msg.sender;
        delete mapOfUnit[val];
        
    }


    function takeAttack(int power) virtual external override {
        tvm.accept();
        callerAddress = msg.sender;
        if (health > power) {
            health = health - power;
            isDied = false;
        }
        else {
            isDied = true;
            callerAddress.transfer(1, true, 160);
        
        }
    }


}
