
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";

contract WarUnit is GameObject {
    

    int public selfPower;

    function setHealth(int val) public virtual override {
        health = val;
    }

    function setPower(int val ) public virtual {
        tvm.accept();
        selfPower = val;
    }


    function attack(GameInterface myAddress ) public {
        tvm.accept();
        myAddress.takeAttack(selfPower);
    }

}
