
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "GameObject.sol";
import "BaseStation.sol";


contract WarUnit is GameObject {

    int public selfPower;
    BaseStation base;
    
   constructor() public override {
        base.addUnit(msg.sender);
     tvm.accept();   
  }

    
    function setHealth(int val) public virtual override {
    health = val;
  }

    function setPower(int val ) public virtual {
        tvm.accept();
        selfPower = val;
    }

    function attack(GameInterface myAddress ) public {
        tvm.accept();
        myAddress.takeAttack(selfPower);
    }

   
    function takeAttack(int power) virtual external override {
        tvm.accept();
        callerAddress = msg.sender;
        if (health > power) {
            health = health - power;
            isDied = false;
        }
        else {
            isDied = true;
           base.delUnit(msg.sender);
            callerAddress.transfer(1, true, 160);
            
        }
    }


}
